cloudPort: ""
httpPort: ""
disableHttps: false

platform:
  databaseProvider: "cockroachdb"

frontend:
  replicas: 1
  runtimeSecret:
    enabled: true
    name: devbox-frontend-runtime
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    gpuEnable: "false"
    gpuSchedulerMode: native
    devboxAffinityEnable: "true"
    enableImportFeature: "true"
    enableWebideFeature: "true"
    enableAdvancedConfig: "true"
    enableAdvancedEnvAndConfigmap: "true"
    enableAdvancedNfs: "true"
    enableAdvancedSharedMemory: "true"
    cpuSlideMarkList: "2,4,8,16,32"
    memorySlideMarkList: "4,8,16,32,64"
    storageLimit: 20Gi
    storageDefault: "20"
    nfsStorageClassName: nfs-csi
    nfsMaxSize: "1000"
    webidePort: "9999"
    customScripts: ""

ingress:
  className: nginx
  hostPrefix: devbox

extraManifests: []
