platform:
  databaseProvider: "cockroachdb"

controller:
  replicas: 1
  requestCpuRate: "20"
  requestMemoryRate: "10"
  matchers:
    enablePodEphemeralStorageMatcher: false
    enablePodAnnotationsMatcher: true
    enablePodEnvMatcher: true
    enablePodResourceMatcher: true
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  defaultUserRoleBinding:
    enabled: true

frontend:
  replicas: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    documentUrlZh: https://sealos.run/docs/overview/intro
    documentUrlEn: https://sealos.io/docs/overview/intro
    privacyUrlZh: https://sealos.run/docs/msa/privacy-policy
    privacyUrlEn: https://sealos.io/docs/msa/privacy-policy
    gpuEnable: "true"
    squashEnable: "false"
    devboxAffinityEnable: "true"
    enableImportFeature: "true"
    enableWebideFeature: "true"
    enabledIDEs: ""
    enableAdvancedEnvAndConfigmap: "true"
    enableAdvancedNfs: "true"
    enableAdvancedSharedMemory: "true"
    cpuSlideMarkList: "2,4,8,16,32"
    memorySlideMarkList: "4,8,16,32,64"
    storageDefault: "20"
    domainChallengeSecret: ""
    nfsStorageClassName: "nfs-csi"
    nfsMaxSize: "1000"
    webidePort: "9999"
    customScripts: ""

ingress:
  className: nginx
  hostPrefix: devbox

extraManifests: []
