/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/sealos-apps/devbox/v1/controller/internal/controller/helper"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/tools/record"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	devboxv1alpha1 "github.com/sealos-apps/devbox/v1/controller/api/v1alpha1"
)

var _ = Describe("Devbox Controller", func() {
	Context("When reconciling a resource", func() {
		const resourceName = "test-resource"

		ctx := context.Background()

		typeNamespacedName := types.NamespacedName{
			Name:      resourceName,
			Namespace: "default", // TODO(user):Modify as needed
		}
		devbox := &devboxv1alpha1.Devbox{}

		BeforeEach(func() {
			By("creating the custom resource for the Kind Devbox")
			err := k8sClient.Get(ctx, typeNamespacedName, devbox)
			if err != nil && errors.IsNotFound(err) {
				resource := &devboxv1alpha1.Devbox{
					ObjectMeta: metav1.ObjectMeta{
						Name:      resourceName,
						Namespace: "default",
					},
					Spec: devboxv1alpha1.DevboxSpec{
						State: devboxv1alpha1.DevboxStateStopped,
						Resource: corev1.ResourceList{
							corev1.ResourceCPU:    resource.MustParse("1"),
							corev1.ResourceMemory: resource.MustParse("1Gi"),
						},
						Image:       "busybox:latest",
						Config:      devboxv1alpha1.Config{},
						NetworkSpec: devboxv1alpha1.NetworkSpec{Type: devboxv1alpha1.NetworkTypeTailnet},
					},
				}
				Expect(k8sClient.Create(ctx, resource)).To(Succeed())
			}
		})

		AfterEach(func() {
			// TODO(user): Cleanup logic after each test, like removing the resource instance.
			resource := &devboxv1alpha1.Devbox{}
			err := k8sClient.Get(ctx, typeNamespacedName, resource)
			Expect(err).NotTo(HaveOccurred())

			By("Cleanup the specific resource instance Devbox")
			Expect(k8sClient.Delete(ctx, resource)).To(Succeed())
		})
		It("should successfully reconcile the resource", func() {
			By("Reconciling the created resource")
			controllerReconciler := &DevboxReconciler{
				Client:   k8sClient,
				Scheme:   k8sClient.Scheme(),
				Recorder: record.NewFakeRecorder(32),
			}

			_, err := controllerReconciler.Reconcile(ctx, reconcile.Request{
				NamespacedName: typeNamespacedName,
			})
			Expect(err).NotTo(HaveOccurred())
			// TODO(user): Add more specific assertions depending on your controller's reconciliation logic.
			// Example: If you expect a certain status condition after reconciliation, verify it here.
		})
	})

	Context("When syncing an existing secret", func() {
		const resourceName = "test-secret-sync"

		ctx := context.Background()
		typeNamespacedName := types.NamespacedName{
			Name:      resourceName,
			Namespace: "default",
		}

		BeforeEach(func() {
			devbox := &devboxv1alpha1.Devbox{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: "default",
				},
				Spec: devboxv1alpha1.DevboxSpec{
					State: devboxv1alpha1.DevboxStateStopped,
					Resource: corev1.ResourceList{
						corev1.ResourceCPU:    resource.MustParse("1"),
						corev1.ResourceMemory: resource.MustParse("1Gi"),
					},
					Image: "busybox:latest",
					Config: devboxv1alpha1.Config{
						Env: []corev1.EnvVar{
							{Name: "FOO", Value: "new-value"},
						},
					},
					NetworkSpec: devboxv1alpha1.NetworkSpec{Type: devboxv1alpha1.NetworkTypeTailnet},
				},
			}
			Expect(k8sClient.Create(ctx, devbox)).To(Succeed())

			secret := &corev1.Secret{
				ObjectMeta: metav1.ObjectMeta{
					Name:      resourceName,
					Namespace: "default",
				},
				Data: map[string][]byte{
					"SEALOS_DEVBOX_JWT_SECRET":      []byte("jwt-secret"),
					"SEALOS_DEVBOX_PUBLIC_KEY":      []byte("public-key"),
					"SEALOS_DEVBOX_PRIVATE_KEY":     []byte("private-key"),
					"SEALOS_DEVBOX_AUTHORIZED_KEYS": []byte("public-key"),
					"SEALOS_DEVBOX_ENV_PROFILE":     []byte("# Generated by Sealos Devbox\nexport FOO=\"old-value\"\n"),
				},
			}
			Expect(k8sClient.Create(ctx, secret)).To(Succeed())
		})

		AfterEach(func() {
			secret := &corev1.Secret{}
			err := k8sClient.Get(ctx, typeNamespacedName, secret)
			if err == nil {
				Expect(k8sClient.Delete(ctx, secret)).To(Succeed())
			} else {
				Expect(errors.IsNotFound(err)).To(BeTrue())
			}

			devbox := &devboxv1alpha1.Devbox{}
			err = k8sClient.Get(ctx, typeNamespacedName, devbox)
			if err == nil {
				Expect(k8sClient.Delete(ctx, devbox)).To(Succeed())
			} else {
				Expect(errors.IsNotFound(err)).To(BeTrue())
			}
		})

		It("should update env profile when devbox env changes", func() {
			devbox := &devboxv1alpha1.Devbox{}
			Expect(k8sClient.Get(ctx, typeNamespacedName, devbox)).To(Succeed())

			controllerReconciler := &DevboxReconciler{
				Client:   k8sClient,
				Scheme:   k8sClient.Scheme(),
				Recorder: record.NewFakeRecorder(32),
			}

			Expect(controllerReconciler.syncSecret(ctx, devbox, map[string]string{"app": resourceName})).To(Succeed())

			secret := &corev1.Secret{}
			Expect(k8sClient.Get(ctx, typeNamespacedName, secret)).To(Succeed())
			Expect(secret.Data["SEALOS_DEVBOX_ENV_PROFILE"]).To(Equal(
				helper.GenerateEnvProfile(devbox, secret.Data["SEALOS_DEVBOX_JWT_SECRET"]),
			))
		})
	})
})
